#!/usr/bin/env python3
"""Bump the release version everywhere it's declared, in one command.

The version lives in three places, and the 0.5.1 release showed what happens
when they're bumped by hand: pyproject.toml and uv.lock silently lagged (the
PEP-723 block and plugin.json moved first). This script is the one path
that's allowed to change the version:

1. plan the edits to pyproject.toml and .claude-plugin/plugin.json (the two
   hand-maintained declarations — uv.lock is derived, regenerated by `uv lock`,
   never hand-edited); both files are written only after both plans succeed,
   so a mid-way plan refusal never leaves a half-edited tree (a failed write
   is reported with restore instructions),
2. regenerate uv.lock so it reflects the new version and dependency pins,
3. re-run scripts/check_version_consistency.py as a self-check before exiting.

It refuses to run if pyproject.toml and plugin.json already disagree — that
state is drift to be fixed, not a starting point.

Usage: python3 scripts/bump_version.py 0.5.2
"""

from __future__ import annotations

import json
import re
import stat
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+([-+][0-9A-Za-z.-]+)?$")
RESTORE = "git checkout pyproject.toml uv.lock .claude-plugin/plugin.json"
SELF_CHECK_TIMEOUT = 60  # the real check runs in ms; this bounds a replaced loop
UV_LOCK_TIMEOUT = 600  # generous: a legit resolution can take minutes; a hung
# one must not stall the bump silently


def _read_text(path: Path) -> str:
    try:
        # The repo files are UTF-8 by contract; reading with an explicit
        # encoding keeps the failure message honest under ASCII locales
        # (locale read_text would mislabel a valid UTF-8 file 'not UTF-8').
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        sys.exit(f"ERROR: {path} not found")
    except OSError as e:
        sys.exit(f"ERROR: {path}: {e}")
    except UnicodeDecodeError as e:
        sys.exit(f"ERROR: {path}: not UTF-8 text: {e}")


def _toml_version(path: Path, text: str) -> str:
    try:
        version = tomllib.loads(text)["project"]["version"]
    except (tomllib.TOMLDecodeError, KeyError, TypeError) as e:
        sys.exit(f"ERROR: {path}: cannot read [project].version: {e}")
    if not isinstance(version, str):
        sys.exit(f"ERROR: {path}: [project].version must be a string")
    return version


def _json_version(path: Path, text: str) -> str:
    try:
        version = json.loads(text)["version"]
    except (json.JSONDecodeError, KeyError, TypeError) as e:
        sys.exit(f'ERROR: {path}: cannot read "version": {e}')
    if not isinstance(version, str):
        sys.exit(f'ERROR: {path}: "version" must be a string')
    return version


def _plan_edit(path: Path, text: str, pattern: re.Pattern[str], new_version: str) -> str:
    """Return the rewritten file text, or exit if the version line isn't unique.

    Operates on the already-read `text`, so the version checked, the plan, and
    the write all share one snapshot. Matching is anchored to a full line
    (patterns carry re.M); a bare `version = "..."` string elsewhere in the
    file can't be hit, and the n != 1 refusal is the safety net for anything
    the anchor misses. The caller writes only after every plan succeeds, so a
    refusal here leaves the files untouched.
    """
    text, n = re.subn(
        pattern,
        lambda m: f"{m.group(1)}{new_version}{m.group(2)}",
        text,
    )
    if n != 1:
        sys.exit(f"ERROR: {path}: expected exactly one matching version line, found {n}")
    return text


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        # ASCII stdout (C locale): don't die printing em-dashes or the U+FFFD
        # replacement chars the gate deliberately echoes.
        sys.stdout.reconfigure(errors="replace")
    if len(sys.argv) != 2 or not VERSION_RE.match(sys.argv[1]):
        sys.exit("usage: python3 scripts/bump_version.py <new-version> (e.g. 0.5.2)")

    new_version = sys.argv[1]
    pyproject = ROOT / "pyproject.toml"
    plugin_json = ROOT / ".claude-plugin/plugin.json"
    check_script = ROOT / "scripts/check_version_consistency.py"

    pyproject_text = _read_text(pyproject)
    plugin_text = _read_text(plugin_json)
    old_version = _toml_version(pyproject, pyproject_text)
    plugin_version = _json_version(plugin_json, plugin_text)
    if old_version != plugin_version:
        sys.exit(
            f"ERROR: pyproject.toml ({old_version}) and plugin.json ({plugin_version}) "
            "disagree — run scripts/check_version_consistency.py and fix the drift first"
        )
    if new_version == old_version:
        # A no-op bump would print 'Bumped 0.5.1 -> 0.5.1' with a commit
        # suggestion while changing nothing — refuse instead. Only refuse when
        # uv.lock agrees too: pyproject/plugin.json can sit at the target with
        # a lagging lock (a failed earlier `uv lock`), and there the bump still
        # has work to do — proceeding lets `uv lock` bring the lock up.
        try:
            lock = tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))
            packages = lock["package"]
            if not isinstance(packages, list) or not all(
                isinstance(p, dict) for p in packages
            ):
                lock_version = None  # wrong-shape lock: proceed, `uv lock` repairs it
            else:
                rtfm_entries = [p for p in packages if p.get("name") == "rtfm"]
                # Mirror the check's count guard: a duplicate first-wins would
                # refuse on a lock the check calls drift.
                lock_version = (
                    rtfm_entries[0].get("version") if len(rtfm_entries) == 1 else None
                )
        except (OSError, tomllib.TOMLDecodeError, KeyError, UnicodeDecodeError):
            lock_version = None
        if lock_version == new_version:
            sys.exit(f"ERROR: already at version {old_version} — nothing to bump")

    # In the lock-only path (old == new) pyproject/plugin.json are rewritten
    # byte-identically and never actually change — the uv-failure branches'
    # restore advice covers only uv.lock (checking out unchanged files would
    # destroy uncommitted edits), and the self-check branches name the check
    # script instead (post_write_advice below).
    lock_only = new_version == old_version
    edited_clause = (
        "uv.lock is stale; pyproject.toml and plugin.json were NOT modified"
        if lock_only
        else "pyproject.toml and plugin.json are already edited"
    )
    lock_restore = "git checkout uv.lock" if lock_only else RESTORE
    # The self-check branches fire after the writes and uv lock completed. In
    # the lock-only path the lock regeneration was the bump's whole point —
    # reverting uv.lock would undo it — so the advice names the check script
    # (the actual problem) and points at verification instead.
    post_write_advice = (
        "The bump completed (uv.lock was regenerated); restore the check script "
        "with: git checkout scripts/check_version_consistency.py, then verify with: "
        "python3 scripts/check_version_consistency.py"
        if lock_only
        else f"Restore with: {RESTORE}"
    )
    # The gate is the one self-check site where the check actually ran and
    # reported: in the lock-only path 'restore the check script' would
    # misdiagnose genuine drift (deps drift between pyproject and the PEP-723
    # block is pre-existing — the bump only pre-checks versions — and is the
    # exact 0.5.1 class). Point at the check's own output instead.
    gate_advice = (
        "The bump's writes and `uv lock` completed, but the tree still fails the "
        "consistency check; fix the drift, then verify with: "
        "python3 scripts/check_version_consistency.py"
        if lock_only
        else f"Restore with: {RESTORE}, then retry: "
        f"python3 scripts/bump_version.py {new_version}"
    )

    # `,?` in the plugin.json pattern echoes the original trailing comma, so the
    # output stays valid JSON whether "version" is the last key in the object
    # or a middle key followed by a comma.
    new_pyproject = _plan_edit(
        pyproject, pyproject_text, re.compile(r'^(version = ")[^"]+(")$', re.M), new_version
    )
    new_plugin = _plan_edit(
        plugin_json, plugin_text, re.compile(r'^(\s*"version": ")[^"]+(",?)$', re.M), new_version
    )
    writes_completed = False
    try:
        try:
            # Explicit UTF-8 on the writes too: the files carry em-dashes, and
            # a locale-encoding write under an ASCII locale truncates the file
            # in open('w') before UnicodeEncodeError — outside this OSError
            # handler.
            # both plans succeeded — commit both writes
            pyproject.write_text(new_pyproject, encoding="utf-8")
            plugin_json.write_text(new_plugin, encoding="utf-8")
            writes_completed = True
        except OSError as e:
            sys.exit(
                f"ERROR: write failed: {e}; pyproject.toml and plugin.json may be half-edited. "
                f"Fix the file state, then restore and retry: {RESTORE} && "
                f"python3 scripts/bump_version.py {new_version}"
            )

        try:
            subprocess.run(["uv", "lock"], cwd=ROOT, check=True, timeout=UV_LOCK_TIMEOUT)
        except subprocess.TimeoutExpired:
            sys.exit(
                f"ERROR: `uv lock` timed out after {UV_LOCK_TIMEOUT}s; {edited_clause}. "
                f"Fix the issue, then restore and retry: "
                f"{lock_restore} && python3 scripts/bump_version.py {new_version}"
            )
        except subprocess.CalledProcessError as e:
            # POSIX subprocess convention: returncode == -signum for signal death.
            why = (
                f"terminated by signal {-e.returncode}"
                if e.returncode < 0
                else f"failed (exit {e.returncode})"
            )
            tail = "Fix the issue" if e.returncode < 0 else "Fix the resolution error"
            sys.exit(
                f"ERROR: `uv lock` {why}; {edited_clause}. {tail}, then restore and "
                f"retry: {lock_restore} && python3 scripts/bump_version.py {new_version}"
            )
        except FileNotFoundError as e:
            # uv missing from PATH — or a wrapper script whose shebang interpreter
            # is gone (execve then fails with ENOENT, same as an absent binary).
            sys.exit(
                f"ERROR: could not run `uv lock`: {e}; uv is missing from PATH or its "
                "wrapper script's interpreter is missing — needed to regenerate uv.lock. "
                f"{edited_clause}. Fix the issue, then restore and retry: "
                f"{lock_restore} && python3 scripts/bump_version.py {new_version}"
            )
        except OSError as e:
            # uv present but not runnable: ENOEXEC (corrupt binary, missing shebang)
            # and EACCES (missing +x bit, noexec mount) are both OSErrors, not
            # CalledProcessError; a wrapper whose shebang interpreter is gone raises
            # FileNotFoundError (ENOENT) and is handled by the branch above.
            sys.exit(
                f"ERROR: could not run `uv lock`: {e}; {edited_clause}. Fix the issue, "
                f"then restore and retry: "
                f"{lock_restore} && python3 scripts/bump_version.py {new_version}"
            )
    except KeyboardInterrupt:
        # A Ctrl-C mid-bump can leave pyproject/plugin.json bumped while uv.lock
        # still resolves the old version — say how to restore, then exit with the
        # hint (SystemExit, no traceback). After the writes complete in the
        # lock-only path the files are byte-identical (never modified), so the
        # advice is scoped to uv.lock there. Ctrl-C during the later self-check
        # phase has its own handler.
        if lock_only and writes_completed:
            sys.exit(
                "ERROR: interrupted; uv.lock is stale and pyproject.toml/plugin.json "
                f"were NOT modified. Restore and retry: {lock_restore} && "
                f"python3 scripts/bump_version.py {new_version}"
            )
        sys.exit(
            f"ERROR: interrupted; pyproject.toml and plugin.json may be edited and uv.lock "
            f"stale. Restore and retry: {RESTORE} && python3 scripts/bump_version.py {new_version}"
        )

    # Reject non-regular files before the probe: open() on a FIFO blocks until
    # a writer appears — a bare stat() can't flag it (stat() succeeds on FIFOs)
    # and the probe can't (it blocks before returning). Directories land here
    # too. Use stat() + S_ISREG rather than exists()/is_file(): pathlib's
    # softened variants return False instead of raising on unreadable paths in
    # Python 3.14+, where the 'cannot be accessed' branch would go dead.
    try:
        st = check_script.stat()
    except FileNotFoundError:
        sys.exit(
            f"ERROR: {check_script} not found — can't self-check. "
            f"{post_write_advice}"
        )
    except OSError as e:  # e.g. an unreadable scripts/ parent directory
        sys.exit(
            f"ERROR: {check_script} cannot be accessed ({e}) — can't self-check. "
            f"{post_write_advice}"
        )
    except KeyboardInterrupt:  # tiny window; the tree is consistent here
        sys.exit("ERROR: interrupted; verify with: python3 scripts/check_version_consistency.py")
    if not stat.S_ISREG(st.st_mode):
        sys.exit(
            f"ERROR: {check_script} is not a regular file — can't self-check. "
            f"{post_write_advice}"
        )
    try:
        with check_script.open("rb") as f:
            f.read(1)  # probe readability — stat() succeeds on chmod-0 files
    except FileNotFoundError:  # race-only now: deleted between stat() and open()
        sys.exit(
            f"ERROR: {check_script} not found — can't self-check. "
            f"{post_write_advice}"
        )
    except OSError as e:
        sys.exit(
            f"ERROR: {check_script} unreadable ({e}) — can't self-check. "
            f"{post_write_advice}"
        )
    except KeyboardInterrupt:  # tiny window; the tree is consistent here
        sys.exit("ERROR: interrupted; verify with: python3 scripts/check_version_consistency.py")
    try:
        # stderr stays inherited so a failing check's diagnostics are visible
        # above the gate; stdout is captured to verify the check really ran
        # (errors="replace": a replaced script emitting raw bytes must not
        # traceback the bump with a decode error).
        check = subprocess.run(
            # -u: a replaced script that prints a clue then hangs must not lose
            # it to block-buffering (Python's stdout is 8K-buffered on a pipe;
            # without -u, TimeoutExpired.output comes back None and the echo is
            # silent).
            [sys.executable, "-u", str(check_script)],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            text=True,
            errors="replace",
            # The real check is in-repo and runs in milliseconds; a long bound
            # converts a replaced looping script from a silent hang into the
            # clean timeout error below.
            timeout=SELF_CHECK_TIMEOUT,
        )
    except subprocess.TimeoutExpired as e:
        out = e.output
        if isinstance(out, bytes):
            # text=True does not decode TimeoutExpired.output — CPython raises
            # with the raw pipe bytes, before the text decode that runs on the
            # success path. Decode with errors="replace", as the run does.
            out = out.decode(errors="replace")
        if out:
            # Same newline handling as the gate's echo: the check's partial
            # output can hold the clue that it was replaced.
            print(out, end="" if out.endswith("\n") else "\n")
        sys.exit(
            f"ERROR: self-check timed out ({SELF_CHECK_TIMEOUT}s); the check script "
            "may be stuck or replaced. Restore it first with: git checkout "
            "scripts/check_version_consistency.py (discards any uncommitted edits "
            "to that file; a no-op on an unmodified script), then verify with: "
            "python3 scripts/check_version_consistency.py"
        )
    except OSError as e:
        sys.exit(
            f"ERROR: could not run the self-check: {e}. {post_write_advice}"
        )
    except KeyboardInterrupt:
        # The bump itself completed; only the verification was cut short. Do not
        # claim the three files agree — the check was interrupted before it
        # could say so, and a silently-diverged uv.lock is exactly its job.
        sys.exit(
            "ERROR: interrupted during the self-check; the bump itself completed "
            "(uv.lock was regenerated); verify with: "
            "python3 scripts/check_version_consistency.py"
        )
    if (
        check.returncode != 0
        or "OK: version and dependency declarations are consistent" not in check.stdout
    ):
        # Requiring the OK verdict (the check script's exact success line — keep
        # the two in sync), not just exit 0, catches a replaced check script
        # (empty file — a /dev/null symlink is already rejected by the S_ISREG
        # guard above) that 'succeeds' without running. Echo the captured
        # stdout: the check's actionable details (per-file versions, per-dep
        # diffs) are on stdout and would otherwise stay invisible.
        if check.stdout:
            # Avoid a double newline after trailing-newline output; keep the
            # ERROR line on its own line.
            print(check.stdout, end="" if check.stdout.endswith("\n") else "\n")
        sys.exit(
            "ERROR: post-bump consistency check did not pass or could not run "
            f"(output above, if any). {gate_advice}"
        )

    if old_version == new_version:
        # The lock-only catch-up path: pyproject/plugin.json were already at
        # the target and only uv.lock was regenerated — no release framing.
        print(
            f"uv.lock regenerated at {new_version}; pyproject.toml and plugin.json "
            f"already at {new_version}."
        )
        print("Commit suggestion:  git add uv.lock && git commit -m \"chore: refresh lockfile\"")
    else:
        print(f"Bumped {old_version} -> {new_version}: pyproject.toml, plugin.json, uv.lock.")
        print(f'Commit suggestion:  git add -u && git commit -m "release: bump to {new_version}"')
    return 0


if __name__ == "__main__":
    sys.exit(main())
