#!/usr/bin/env python3
"""Bump the release version everywhere it's declared, in one command.

The version lives in three places, and the 0.5.1 release showed what happens
when they're bumped by hand: plugin.json and uv.lock silently lagged. This
script is the one path that's allowed to change the version:

1. edit pyproject.toml and .claude-plugin/plugin.json (the two hand-maintained
   declarations — uv.lock is derived and regenerated by `uv lock`, never hand-edited),
2. regenerate uv.lock so it reflects the new version and dependency pins,
3. re-run scripts/check_version_consistency.py as a self-check before exiting.

It refuses to run if pyproject.toml and plugin.json already disagree — that
state is drift to be fixed, not a starting point.

Usage: python3 scripts/bump_version.py 0.5.2
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+([-+][0-9A-Za-z.-]+)?$")


def _edit_version(path: Path, pattern: re.Pattern[str], new_version: str) -> None:
    """Replace the one matching version line in `path`, anchored to the line so a
    bare `version = "..."` elsewhere in the file can never be hit. Refuses on any
    count other than 1."""
    text = path.read_text()
    text, n = re.subn(
        pattern,
        lambda m: f"{m.group(1)}{new_version}{m.group(2)}",
        text,
    )
    if n != 1:
        sys.exit(f"ERROR: {path}: expected exactly one matching version line, found {n}")
    path.write_text(text)


def main() -> int:
    if len(sys.argv) != 2 or not VERSION_RE.match(sys.argv[1]):
        sys.exit("usage: python3 scripts/bump_version.py <new-version> (e.g. 0.5.2)")

    new_version = sys.argv[1]
    pyproject = ROOT / "pyproject.toml"
    plugin_json = ROOT / ".claude-plugin/plugin.json"

    old_version = tomllib.loads(pyproject.read_text())["project"]["version"]
    plugin_version = json.loads(plugin_json.read_text())["version"]
    if old_version != plugin_version:
        sys.exit(
            f"ERROR: pyproject.toml ({old_version}) and plugin.json ({plugin_version}) disagree — "
            "run scripts/check_version_consistency.py and fix the drift first"
        )

    # `,"?` in the plugin.json pattern echoes the original trailing comma, so the
    # output stays valid JSON even when "version" is the last key in the object.
    _edit_version(pyproject, re.compile(r'^(version = ")[^"]+(")$', re.M), new_version)
    _edit_version(plugin_json, re.compile(r'^(\s*"version": ")[^"]+(",?)$', re.M), new_version)

    try:
        subprocess.run(["uv", "lock"], cwd=ROOT, check=True)
    except subprocess.CalledProcessError as e:
        sys.exit(
            f"ERROR: `uv lock` failed (exit {e.returncode}); pyproject.toml and plugin.json "
            "are already edited. Fix the resolution error, then restore and retry: "
            "git checkout pyproject.toml .claude-plugin/plugin.json && "
            f"python3 scripts/bump_version.py {new_version}"
        )
    except FileNotFoundError:
        sys.exit("ERROR: `uv` not found on PATH — needed to regenerate uv.lock")

    check = subprocess.run(
        [sys.executable, str(ROOT / "scripts/check_version_consistency.py")], cwd=ROOT
    )
    if check.returncode != 0:
        sys.exit("ERROR: post-bump consistency check failed (see output above)")

    print(f"Bumped {old_version} -> {new_version}: pyproject.toml, plugin.json, uv.lock.")
    print(f'Commit suggestion:  git add -u && git commit -m "release: bump to {new_version}"')
    return 0


if __name__ == "__main__":
    sys.exit(main())
