#!/usr/bin/env python3
"""Bump the release version everywhere it's declared, in one command.

The version lives in three places, and the 0.5.1 release showed what happens
when they're bumped by hand: plugin.json and uv.lock silently lagged. This
script is the one path that's allowed to change the version:

1. plan the edits to pyproject.toml and .claude-plugin/plugin.json (the two
   hand-maintained declarations — uv.lock is derived, regenerated by `uv lock`,
   never hand-edited); both files are written only after both plans succeed,
   so a mid-way refusal never leaves a half-edited tree,
2. regenerate uv.lock so it reflects the new version and dependency pins,
3. re-run scripts/check_version_consistency.py as a self-check before exiting.

It refuses to run if pyproject.toml and plugin.json already disagree — that
state is drift to be fixed, not a starting point.

Usage: python3 scripts/bump_version.py 0.5.2
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION_RE = re.compile(r"^\d+\.\d+\.\d+([-+][0-9A-Za-z.-]+)?$")


def _read_toml_version(path: Path) -> str:
    try:
        return tomllib.loads(path.read_text())["project"]["version"]
    except FileNotFoundError:
        sys.exit(f"ERROR: {path} not found")
    except OSError as e:
        sys.exit(f"ERROR: {path}: {e}")
    except (tomllib.TOMLDecodeError, KeyError) as e:
        sys.exit(f"ERROR: {path}: cannot read [project].version: {e}")


def _read_json_version(path: Path) -> str:
    try:
        return json.loads(path.read_text())["version"]
    except FileNotFoundError:
        sys.exit(f"ERROR: {path} not found")
    except OSError as e:
        sys.exit(f"ERROR: {path}: {e}")
    except (json.JSONDecodeError, KeyError) as e:
        sys.exit(f'ERROR: {path}: cannot read "version": {e}')


def _plan_edit(path: Path, pattern: re.Pattern[str], new_version: str) -> str:
    """Return the rewritten file text, or exit if the version line isn't unique.

    Matching is anchored to a full line (patterns carry re.M); a bare `version
    = "..."` string elsewhere in the file can't be hit, and the n != 1 refusal
    is the safety net for anything the anchor misses. The caller writes only
    after every plan succeeds, so a refusal here leaves the files untouched.
    """
    text = path.read_text()
    text, n = re.subn(
        pattern,
        lambda m: f"{m.group(1)}{new_version}{m.group(2)}",
        text,
    )
    if n != 1:
        sys.exit(f"ERROR: {path}: expected exactly one matching version line, found {n}")
    return text


def main() -> int:
    if len(sys.argv) != 2 or not VERSION_RE.match(sys.argv[1]):
        sys.exit("usage: python3 scripts/bump_version.py <new-version> (e.g. 0.5.2)")

    new_version = sys.argv[1]
    pyproject = ROOT / "pyproject.toml"
    plugin_json = ROOT / ".claude-plugin/plugin.json"
    check_script = ROOT / "scripts/check_version_consistency.py"

    old_version = _read_toml_version(pyproject)
    plugin_version = _read_json_version(plugin_json)
    if old_version != plugin_version:
        sys.exit(
            f"ERROR: pyproject.toml ({old_version}) and plugin.json ({plugin_version}) "
            "disagree — run scripts/check_version_consistency.py and fix the drift first"
        )

    # `,?` in the plugin.json pattern echoes the original trailing comma, so the
    # output stays valid JSON whether "version" is the last key in the object
    # or a middle key followed by a comma.
    new_pyproject = _plan_edit(pyproject, re.compile(r'^(version = ")[^"]+(")$', re.M), new_version)
    new_plugin = _plan_edit(
        plugin_json, re.compile(r'^(\s*"version": ")[^"]+(",?)$', re.M), new_version
    )
    pyproject.write_text(new_pyproject)  # both plans succeeded — commit both writes
    plugin_json.write_text(new_plugin)

    try:
        subprocess.run(["uv", "lock"], cwd=ROOT, check=True)
    except subprocess.CalledProcessError as e:
        sys.exit(
            f"ERROR: `uv lock` failed (exit {e.returncode}); pyproject.toml and plugin.json "
            "are already edited. Fix the resolution error, then restore and retry: "
            "git checkout pyproject.toml .claude-plugin/plugin.json && "
            f"python3 scripts/bump_version.py {new_version}"
        )
    except FileNotFoundError:
        sys.exit("ERROR: `uv` not found on PATH — needed to regenerate uv.lock")

    if not check_script.exists():
        sys.exit(
            f"ERROR: {check_script} not found — can't self-check. Restore the edited "
            "files with: git checkout pyproject.toml .claude-plugin/plugin.json"
        )
    check = subprocess.run([sys.executable, str(check_script)], cwd=ROOT)
    if check.returncode != 0:
        sys.exit(
            "ERROR: post-bump consistency check failed (see output above); restore the "
            "edited files with: git checkout pyproject.toml .claude-plugin/plugin.json"
        )

    print(f"Bumped {old_version} -> {new_version}: pyproject.toml, plugin.json, uv.lock.")
    print(f'Commit suggestion:  git add -u && git commit -m "release: bump to {new_version}"')
    return 0


if __name__ == "__main__":
    sys.exit(main())
